trigger:
  batch: true
  branches:
    include:
    - main
    - 'v*.*'
    - 'validate/*'
  paths:
    exclude:
    - doc/
    - docs/
    - '*.md'
    - .vscode/
    - .github/
    - azure-pipelines/release.yml

parameters:
- name: includeMacOS
  displayName: Build on macOS
  type: boolean
  default: true # macOS is often bogged down in Azure Pipelines
- name: RunTests
  displayName: Run tests
  type: boolean
  default: true
- name: ProductionBuild
  type: string
  default: 'Testing' 
- name: XCodePath
  type: string
  default: '/Applications/Xcode_16.2.app' 
- name: WindowsAgentPool
  displayName: Build Pool for Windows host
  type: string
  default: 'Local Windows'  
- name: MacAgentPool
  displayName: Build Pool for macOS host
  type: string
  default: '' 
- name: CertSecurePwd
  displayName: Password for Apple certificate
  type: string
  default: $(CertSecurePwd)
- name: RunDotNetFormatWin
  displayName: Run dotnet format on windows
  type: boolean
  default: true
- name: RunDotNetFormatMac
  displayName: Run dotnet format on macos
  type: boolean
  default: false
  
variables:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true

  codecov_token: '5a7f688f-2863-461e-b3aa-8c65c41b4159'
  ci_feed: 'https://pkgs.dev.azure.com/NetworkVisor/_packaging/networkvisor-eng/nuget/v3/index.json'
  NUGET_PACKAGES: $(Agent.TempDirectory)/.nuget/packages/

jobs:
- template: azure-pipelines/build.yml
  parameters:
    includeMacOS: ${{ parameters.includeMacOS }}
    RunTests: ${{ parameters.RunTests }}
    ProductionBuild: ${{ parameters.ProductionBuild }}
    XCodePath: ${{ parameters.XCodePath }}
    WindowsAgentPool: ${{ parameters.WindowsAgentPool }}
    MacAgentPool: ${{ parameters.MacAgentPool }}
    CertSecurePwd: ${{ parameters.CertSecurePwd }}
    RunDotNetFormatWin: ${{ parameters.RunDotNetFormatWin }}
    RunDotNetFormatMac: ${{ parameters.RunDotNetFormatMac }}
    