parameters:
  windowsPool: Local Windows
  jobTimeout : 30
  includeMacOS:
  includeLinux:

jobs:
- job: Windows
  timeoutInMinutes: ${{ parameters.jobTimeout }}
  pool: ${{ parameters.windowsPool }}
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -InstallMaui -InstallXHarnessTool

  - powershell: '& (./azure-pipelines/Get-nbgv.ps1) cloud'
    displayName: Set build number

  - template: dotnet.yml
    parameters:
      test_filter: '--filter "Category=Windows"'
      build_configuration: 'Release-Windows'

  - template: expand-template.yml

- job: Linux
  condition: ${{ parameters.includeLinux }}
  timeoutInMinutes: ${{ parameters.jobTimeout }}
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -InstallXHarnessTool -NoRestore

  - template: dotnet.yml
    parameters:
      test_filter: '--filter "Category=Linux"'
      build_configuration: 'Release-Linux'

  - template: expand-template.yml

- job: macOS
  condition: ${{ parameters.includeMacOS }}
  timeoutInMinutes: ${{ parameters.jobTimeout }}
  pool:
    vmImage: macOS-latest
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -InstallMaui -InstallXHarnessTool
      
  - template: dotnet.yml
    parameters:
      test_filter: '--filter "Category=MacOS"'
      build_configuration: 'Release-MacOS'

  - template: expand-template.yml

- job: WrapUp
  timeoutInMinutes: ${{ parameters.jobTimeout }}
  dependsOn:
  - Windows
  - Linux
  - macOS
  pool:
    vmImage: ubuntu-latest
  condition: succeededOrFailed()
  steps:
  - checkout: self
    clean: true
  - template: install-dependencies.yml
    parameters:
      initArgs: -NoRestore
  - template: publish-codecoverage.yml
    parameters:
      includeMacOS: ${{ parameters.includeMacOS }}
      includeLinux: ${{ parameters.includeLinux }}
  - template: publish-deployables.yml
