steps:
- task: MicroBuildSigningPlugin@3
  inputs:
    signType: $(SignType)
    zipSources: false
  displayName: Install MicroBuild Signing Plugin

- task: MicroBuildLocalizationPlugin@3
  inputs:
    languages: $(LocLanguages)
  displayName: Install MicroBuild Localization Plugin
